import type { MatchEvent } from "@/types/events";
import type { MatchWithEvents } from "@/types/match";
import type {
  ShotAttemptsByPeriod,
  StallPeriodBreakdown,
  TeamPeriodStat,
  WrestlerPeriodBreakdown,
  WrestlerSeasonStats,
} from "@/types/analytics";
import type { Wrestler } from "@/types/wrestler";

const basePeriodStats: WrestlerPeriodBreakdown[] = [
  {
    periodLabel: "Period 1",
    periodOrder: 1,
    takedownsFor: 12,
    takedownsAgainst: 6,
    attemptsFor: 28,
    attemptsAgainst: 18,
    pointsDifferential: 2.4,
    matchesLogged: 10,
  },
  {
    periodLabel: "Period 2",
    periodOrder: 2,
    takedownsFor: 9,
    takedownsAgainst: 8,
    attemptsFor: 22,
    attemptsAgainst: 20,
    pointsDifferential: 0.8,
    matchesLogged: 10,
  },
  {
    periodLabel: "Period 3",
    periodOrder: 3,
    takedownsFor: 6,
    takedownsAgainst: 7,
    attemptsFor: 16,
    attemptsAgainst: 18,
    pointsDifferential: -0.4,
    matchesLogged: 10,
  },
  {
    periodLabel: "OT",
    periodOrder: 4,
    takedownsFor: 2,
    takedownsAgainst: 1,
    attemptsFor: 4,
    attemptsAgainst: 3,
    pointsDifferential: 0.6,
    matchesLogged: 4,
  },
];

const defaultShotAttempts: ShotAttemptsByPeriod[] = [
  { label: "Period 1", order: 1, attempts: 2.4 },
  { label: "Period 2", order: 2, attempts: 1.6 },
  { label: "Period 3", order: 3, attempts: 1.2 },
];

const defaultStallBreakdown: StallPeriodBreakdown[] = [
  { label: "Period 1", order: 1, us: 0.6, opponent: 0.4, matchesLogged: 10 },
  { label: "Period 2", order: 2, us: 0.5, opponent: 0.6, matchesLogged: 10 },
  { label: "Period 3", order: 3, us: 0.3, opponent: 0.5, matchesLogged: 10 },
  { label: "OT", order: 4, us: 0.2, opponent: 0.3, matchesLogged: 4 },
];

export const mockWrestlers: Wrestler[] = [
  {
    id: 1,
    name: "Ethan Blake",
    classYear: "2026",
    primaryWeightClass: "133",
    active: true,
  },
  {
    id: 2,
    name: "Miles Carter",
    classYear: "2025",
    primaryWeightClass: "149",
    active: true,
  },
  {
    id: 3,
    name: "Jackson Rivera",
    classYear: "2024",
    primaryWeightClass: "165",
    active: true,
  },
  {
    id: 4,
    name: "Logan Smith",
    classYear: "2027",
    primaryWeightClass: "184",
    active: true,
  },
];

const sampsonEvents: MatchEvent[] = [
  {
    id: "evt-1",
    actionType: "takedown",
    periodOrder: 1,
    periodType: "reg",
    periodNumber: 1,
    scorer: "us",
    takedownType: "double",
  },
  {
    id: "evt-2",
    actionType: "escape",
    periodOrder: 2,
    periodType: "reg",
    periodNumber: 1,
    scorer: "opponent",
  },
  {
    id: "evt-3",
    actionType: "nearfall",
    periodOrder: 3,
    periodType: "reg",
    periodNumber: 2,
    scorer: "us",
    points: 3,
  },
];

export const mockMatches: MatchWithEvents[] = [
  {
    id: 501,
    wrestlerId: 1,
    wrestlerName: "Ethan Blake",
    opponentName: "UNC-Charlotte",
    opponentSchool: "UNC-Charlotte",
    weightClass: "133",
    matchType: "dual",
    date: "2025-02-08",
    result: "W",
    ourScore: 12,
    opponentScore: 5,
    firstTakedownScorer: "us",
    events: sampsonEvents,
  },
  {
    id: 502,
    wrestlerId: 2,
    wrestlerName: "Miles Carter",
    opponentName: "Gardner-Webb",
    opponentSchool: "Gardner-Webb",
    weightClass: "149",
    matchType: "dual",
    date: "2025-02-08",
    result: "L",
    ourScore: 5,
    opponentScore: 7,
    firstTakedownScorer: "opponent",
    events: [
      {
        id: "evt-4",
        actionType: "takedown_attempt",
        periodOrder: 1,
        periodType: "reg",
        periodNumber: 1,
        scorer: "none",
        attacker: "us",
        takedownType: "sweep_single",
      },
      {
        id: "evt-5",
        actionType: "escape",
        periodOrder: 2,
        periodType: "reg",
        periodNumber: 2,
        scorer: "us",
      },
    ],
  },
  {
    id: 503,
    wrestlerId: 3,
    wrestlerName: "Jackson Rivera",
    opponentName: "App State",
    opponentSchool: "Appalachian State",
    weightClass: "165",
    matchType: "dual",
    date: "2025-02-01",
    result: "W",
    ourScore: 9,
    opponentScore: 2,
    firstTakedownScorer: "us",
    events: [
      {
        id: "evt-6",
        actionType: "takedown",
        periodOrder: 1,
        periodType: "reg",
        periodNumber: 1,
        scorer: "us",
        takedownType: "front_head",
      },
      {
        id: "evt-7",
        actionType: "escape",
        periodOrder: 2,
        periodType: "reg",
        periodNumber: 1,
        scorer: "opponent",
      },
    ],
  },
];

export const mockTeamPeriodStats: TeamPeriodStat[] = [
  {
    periodLabel: "Period 1",
    periodOrder: 1,
    takedownsFor: 42,
    takedownsAgainst: 28,
    attemptsFor: 88,
    attemptsAgainst: 65,
    pointsDifferential: 3.9,
    matchesLogged: 20,
  },
  {
    periodLabel: "Period 2",
    periodOrder: 2,
    takedownsFor: 28,
    takedownsAgainst: 31,
    attemptsFor: 61,
    attemptsAgainst: 59,
    pointsDifferential: 0.4,
    matchesLogged: 20,
  },
  {
    periodLabel: "Period 3",
    periodOrder: 3,
    takedownsFor: 19,
    takedownsAgainst: 25,
    attemptsFor: 43,
    attemptsAgainst: 57,
    pointsDifferential: -1.2,
    matchesLogged: 20,
  },
  {
    periodLabel: "OT",
    periodOrder: 4,
    takedownsFor: 6,
    takedownsAgainst: 2,
    attemptsFor: 10,
    attemptsAgainst: 7,
    pointsDifferential: 1.6,
    matchesLogged: 5,
  },
];

export const mockWrestlerStats: Record<number, WrestlerSeasonStats> = {
  1: {
    wrestler: mockWrestlers[0],
    record: "18-4",
    winPercentage: 0.82,
    totalPointsFor: 112,
    totalPointsAgainst: 74,
    firstTakedownWinPct: 0.78,
    ridingTimeAdvantagePct: 0.64,
    matches: mockMatches.filter((match) => match.wrestlerId === 1),
    periods: basePeriodStats,
    overall: {
      pointsFor: 112,
      pointsAgainst: 74,
      escapesFor: 36,
      escapesAgainst: 22,
      nearfallPointsFor: 28,
      nearfallPointsAgainst: 12,
      decisionWins: 10,
      majorDecisionWins: 4,
      techFallWins: 2,
      fallWins: 2,
    },
    outcomePredictors: {
      firstTakedownWinPct: 0.78,
      leadingAfterP1WinPct: 0.81,
      trailingAfterP1WinPct: 0.55,
      tiedHeadingIntoP3WinPct: 0.7,
      averagePointsByPeriod: [
        { label: "Period 1", order: 1, us: 3.4, opponent: 1.8 },
        { label: "Period 2", order: 2, us: 2.6, opponent: 1.9 },
        { label: "Period 3", order: 3, us: 2.1, opponent: 1.6 },
      ],
    },
    takedownEfficiency: {
      ourConversionPct: 0.62,
      opponentConversionPct: 0.41,
      ourTakedowns: 62,
      ourAttempts: 38,
      mostCommonTakedown: {
        type: "double",
        total: 26,
        avgPerMatch: 1.3,
      },
      mostCommonShot: {
        type: "double",
        total: 34,
        avgPerMatch: 1.7,
      },
      avgTakedownsInP3: { us: 0.8, opponent: 0.4 },
      shotAttemptsByPeriod: defaultShotAttempts,
    },
    topBottom: {
      zeroEscapePct: 0.18,
      rideOutAvg: { us: 0.4, opponent: 0.2 },
      ridingTimePointPct: { us: 0.55, opponent: 0.25 },
      reversalsAvg: { us: 0.6, opponent: 0.4 },
      nearfallAvg: { us: 1.4, opponent: 0.6 },
    },
    stall: {
      avgUs: 0.8,
      avgOpponent: 1.2,
      byPeriod: defaultStallBreakdown,
    },
    clutch: {
      overtimeWinPct: 0.67,
      threePointMarginWinPct: 0.72,
    },
    recentMatches: mockMatches.filter((match) => match.wrestlerId === 1),
  },
  2: {
    wrestler: mockWrestlers[1],
    record: "16-6",
    winPercentage: 0.72,
    totalPointsFor: 98,
    totalPointsAgainst: 77,
    firstTakedownWinPct: 0.68,
    ridingTimeAdvantagePct: 0.47,
    matches: mockMatches.filter((match) => match.wrestlerId === 2),
    periods: basePeriodStats,
    overall: {
      pointsFor: 98,
      pointsAgainst: 77,
      escapesFor: 30,
      escapesAgainst: 27,
      nearfallPointsFor: 18,
      nearfallPointsAgainst: 16,
      decisionWins: 9,
      majorDecisionWins: 3,
      techFallWins: 2,
      fallWins: 2,
    },
    outcomePredictors: {
      firstTakedownWinPct: 0.68,
      leadingAfterP1WinPct: 0.74,
      trailingAfterP1WinPct: 0.42,
      tiedHeadingIntoP3WinPct: 0.6,
      averagePointsByPeriod: [
        { label: "Period 1", order: 1, us: 3.0, opponent: 2.1 },
        { label: "Period 2", order: 2, us: 2.2, opponent: 2.0 },
        { label: "Period 3", order: 3, us: 1.8, opponent: 1.7 },
      ],
    },
    takedownEfficiency: {
      ourConversionPct: 0.57,
      opponentConversionPct: 0.44,
      ourTakedowns: 57,
      ourAttempts: 43,
      mostCommonTakedown: {
        type: "sweep_single",
        total: 20,
        avgPerMatch: 1.0,
      },
      mostCommonShot: {
        type: "sweep_single",
        total: 28,
        avgPerMatch: 1.4,
      },
      avgTakedownsInP3: { us: 0.6, opponent: 0.7 },
      shotAttemptsByPeriod: defaultShotAttempts,
    },
    topBottom: {
      zeroEscapePct: 0.22,
      rideOutAvg: { us: 0.3, opponent: 0.35 },
      ridingTimePointPct: { us: 0.4, opponent: 0.3 },
      reversalsAvg: { us: 0.4, opponent: 0.5 },
      nearfallAvg: { us: 0.9, opponent: 0.8 },
    },
    stall: {
      avgUs: 0.9,
      avgOpponent: 1.0,
      byPeriod: defaultStallBreakdown,
    },
    clutch: {
      overtimeWinPct: 0.5,
      threePointMarginWinPct: 0.63,
    },
    recentMatches: mockMatches.filter((match) => match.wrestlerId === 2),
  },
  3: {
    wrestler: mockWrestlers[2],
    record: "20-3",
    winPercentage: 0.87,
    totalPointsFor: 134,
    totalPointsAgainst: 61,
    firstTakedownWinPct: 0.74,
    ridingTimeAdvantagePct: 0.7,
    matches: mockMatches.filter((match) => match.wrestlerId === 3),
    periods: basePeriodStats,
    overall: {
      pointsFor: 134,
      pointsAgainst: 61,
      escapesFor: 42,
      escapesAgainst: 18,
      nearfallPointsFor: 34,
      nearfallPointsAgainst: 9,
      decisionWins: 12,
      majorDecisionWins: 4,
      techFallWins: 3,
      fallWins: 1,
    },
    outcomePredictors: {
      firstTakedownWinPct: 0.74,
      leadingAfterP1WinPct: 0.86,
      trailingAfterP1WinPct: 0.58,
      tiedHeadingIntoP3WinPct: 0.8,
      averagePointsByPeriod: [
        { label: "Period 1", order: 1, us: 3.8, opponent: 1.2 },
        { label: "Period 2", order: 2, us: 3.0, opponent: 1.5 },
        { label: "Period 3", order: 3, us: 2.4, opponent: 1.1 },
      ],
    },
    takedownEfficiency: {
      ourConversionPct: 0.68,
      opponentConversionPct: 0.35,
      ourTakedowns: 68,
      ourAttempts: 32,
      mostCommonTakedown: {
        type: "front_head",
        total: 24,
        avgPerMatch: 1.2,
      },
      mostCommonShot: {
        type: "high_c",
        total: 30,
        avgPerMatch: 1.5,
      },
      avgTakedownsInP3: { us: 0.9, opponent: 0.3 },
      shotAttemptsByPeriod: defaultShotAttempts,
    },
    topBottom: {
      zeroEscapePct: 0.12,
      rideOutAvg: { us: 0.5, opponent: 0.15 },
      ridingTimePointPct: { us: 0.66, opponent: 0.2 },
      reversalsAvg: { us: 0.7, opponent: 0.3 },
      nearfallAvg: { us: 1.7, opponent: 0.4 },
    },
    stall: {
      avgUs: 0.7,
      avgOpponent: 0.9,
      byPeriod: defaultStallBreakdown,
    },
    clutch: {
      overtimeWinPct: 0.75,
      threePointMarginWinPct: 0.78,
    },
    recentMatches: mockMatches.filter((match) => match.wrestlerId === 3),
  },
};
