import type { MatchEvent } from "@/types/events";
import type { MatchWithEvents } from "@/types/match";
import type {
  TeamDashboardData,
  WrestlerSeasonStats,
} from "@/types/analytics";
import type { Wrestler } from "@/types/wrestler";

export const mockWrestlers: Wrestler[] = [
  {
    id: 1,
    name: "Ethan Blake",
    classYear: "2026",
    primaryWeightClass: "133",
    active: true,
  },
  {
    id: 2,
    name: "Miles Carter",
    classYear: "2025",
    primaryWeightClass: "149",
    active: true,
  },
  {
    id: 3,
    name: "Jackson Rivera",
    classYear: "2024",
    primaryWeightClass: "165",
    active: true,
  },
  {
    id: 4,
    name: "Logan Smith",
    classYear: "2027",
    primaryWeightClass: "184",
    active: true,
  },
];

const sampsonEvents: MatchEvent[] = [
  {
    id: "evt-1",
    actionType: "takedown",
    periodOrder: 1,
    periodType: "reg",
    periodNumber: 1,
    scorer: "us",
    takedownType: "double",
  },
  {
    id: "evt-2",
    actionType: "escape",
    periodOrder: 2,
    periodType: "reg",
    periodNumber: 1,
    scorer: "opponent",
  },
  {
    id: "evt-3",
    actionType: "nearfall",
    periodOrder: 3,
    periodType: "reg",
    periodNumber: 2,
    scorer: "us",
    points: 3,
  },
];

export const mockMatches: MatchWithEvents[] = [
  {
    id: 501,
    wrestlerId: 1,
    wrestlerName: "Ethan Blake",
    opponentName: "UNC-Charlotte",
    opponentSchool: "UNC-Charlotte",
    weightClass: "133",
    matchType: "dual",
    date: "2025-02-08",
    result: "W",
    ourScore: 12,
    opponentScore: 5,
    firstTakedownScorer: "us",
    events: sampsonEvents,
  },
  {
    id: 502,
    wrestlerId: 2,
    wrestlerName: "Miles Carter",
    opponentName: "Gardner-Webb",
    opponentSchool: "Gardner-Webb",
    weightClass: "149",
    matchType: "dual",
    date: "2025-02-08",
    result: "L",
    ourScore: 5,
    opponentScore: 7,
    firstTakedownScorer: "opponent",
    events: [
      {
        id: "evt-4",
        actionType: "takedown_attempt",
        periodOrder: 1,
        periodType: "reg",
        periodNumber: 1,
        scorer: "none",
        attacker: "us",
        takedownType: "single",
      },
      {
        id: "evt-5",
        actionType: "escape",
        periodOrder: 2,
        periodType: "reg",
        periodNumber: 2,
        scorer: "us",
      },
    ],
  },
  {
    id: 503,
    wrestlerId: 3,
    wrestlerName: "Jackson Rivera",
    opponentName: "App State",
    opponentSchool: "Appalachian State",
    weightClass: "165",
    matchType: "dual",
    date: "2025-02-01",
    result: "W",
    ourScore: 9,
    opponentScore: 2,
    firstTakedownScorer: "us",
    events: [
      {
        id: "evt-6",
        actionType: "takedown",
        periodOrder: 1,
        periodType: "reg",
        periodNumber: 1,
        scorer: "us",
        takedownType: "single",
      },
      {
        id: "evt-7",
        actionType: "escape",
        periodOrder: 2,
        periodType: "reg",
        periodNumber: 1,
        scorer: "opponent",
      },
    ],
  },
];

export const mockTeamDashboard: TeamDashboardData = {
  seasonLabel: "2024-25 Regular Season",
  record: "9-3",
  matchesLogged: 58,
  totalPointsFor: 192,
  totalPointsAgainst: 141,
  firstTakedownWinPct: 0.71,
  ridingTimeAdvantagePct: 0.64,
  periodStats: [
    {
      periodLabel: "Period 1",
      periodOrder: 1,
      takedownsFor: 42,
      takedownsAgainst: 28,
      attemptsFor: 88,
      attemptsAgainst: 65,
      pointsDifferential: 3.9,
    },
    {
      periodLabel: "Period 2",
      periodOrder: 2,
      takedownsFor: 28,
      takedownsAgainst: 31,
      attemptsFor: 61,
      attemptsAgainst: 59,
      pointsDifferential: 0.4,
    },
    {
      periodLabel: "Period 3",
      periodOrder: 3,
      takedownsFor: 19,
      takedownsAgainst: 25,
      attemptsFor: 43,
      attemptsAgainst: 57,
      pointsDifferential: -1.2,
    },
    {
      periodLabel: "OT",
      periodOrder: 4,
      takedownsFor: 6,
      takedownsAgainst: 2,
      attemptsFor: 10,
      attemptsAgainst: 7,
      pointsDifferential: 1.6,
    },
  ],
  leaderboards: {
    wins: [
      { id: 1, label: "Ethan Blake", value: "18-4", helper: "82% win rate" },
      { id: 2, label: "Miles Carter", value: "16-6", helper: "73% win rate" },
    ],
    takedowns: [
      { id: 3, label: "Jackson Rivera", value: "41", helper: "2.1 per match" },
      { id: 4, label: "Logan Smith", value: "38", helper: "1.9 per match" },
    ],
    thirdPeriod: [
      { id: 5, label: "Ethan Blake", value: "+18", helper: "3rd period diff" },
      { id: 2, label: "Miles Carter", value: "+11", helper: "3rd period diff" },
    ],
    firstTakedown: [
      { id: 3, label: "Jackson Rivera", value: "78%", helper: "Min 8 matches" },
      { id: 1, label: "Ethan Blake", value: "74%", helper: "Min 8 matches" },
    ],
  },
  recentMatches: mockMatches,
};

export const mockWrestlerStats: Record<number, WrestlerSeasonStats> = {
  1: {
    wrestler: mockWrestlers[0],
    record: "18-4",
    winPercentage: 0.82,
    totalPointsFor: 112,
    totalPointsAgainst: 74,
    firstTakedownWinPct: 0.78,
    ridingTimeAdvantagePct: 0.64,
    matches: mockMatches.filter((match) => match.wrestlerId === 1),
    periods: [
      {
        periodLabel: "Period 1",
        periodOrder: 1,
        takedownsFor: 18,
        takedownsAgainst: 9,
        attemptsFor: 34,
        attemptsAgainst: 22,
        pointsDifferential: 2.7,
      },
      {
        periodLabel: "Period 2",
        periodOrder: 2,
        takedownsFor: 11,
        takedownsAgainst: 12,
        attemptsFor: 27,
        attemptsAgainst: 25,
        pointsDifferential: 0.8,
      },
      {
        periodLabel: "Period 3",
        periodOrder: 3,
        takedownsFor: 7,
        takedownsAgainst: 6,
        attemptsFor: 18,
        attemptsAgainst: 16,
        pointsDifferential: 1.1,
      },
    ],
  },
  2: {
    wrestler: mockWrestlers[1],
    record: "16-6",
    winPercentage: 0.72,
    totalPointsFor: 98,
    totalPointsAgainst: 77,
    firstTakedownWinPct: 0.68,
    ridingTimeAdvantagePct: 0.47,
    matches: mockMatches.filter((match) => match.wrestlerId === 2),
    periods: [
      {
        periodLabel: "Period 1",
        periodOrder: 1,
        takedownsFor: 15,
        takedownsAgainst: 12,
        attemptsFor: 33,
        attemptsAgainst: 30,
        pointsDifferential: 1.6,
      },
      {
        periodLabel: "Period 2",
        periodOrder: 2,
        takedownsFor: 8,
        takedownsAgainst: 11,
        attemptsFor: 21,
        attemptsAgainst: 27,
        pointsDifferential: -0.4,
      },
      {
        periodLabel: "Period 3",
        periodOrder: 3,
        takedownsFor: 6,
        takedownsAgainst: 9,
        attemptsFor: 19,
        attemptsAgainst: 22,
        pointsDifferential: -0.9,
      },
    ],
  },
};
